import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../Data/education.json'
import { useState } from 'react'
import Card from '../Components/Card'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(data);
  const [information, setInformation] = useState([...data])

  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p className='about-btn'>
           <Link className='about-btn' href="about">About</Link>
          </p>
         

        <div className={styles.grid}>
          <div className='title1'>Business Degrees</div>
          {information && information.map((info, index) => {
            if(info.department === "Business")
            return(
              <Card key={index} degree={info.degree} colour="red" font="10px"/>
            )
          
          })}

        <div className='title2'>Computing Degrees</div>
          {information && information.map((info, index) => {
            if(info.department === "Computing")
            return(
              <Card key={index} degree={info.degree} colour="blue" font="12px"/>
            )
          
          })}


         
        </div>
      </main>
    </>
  )
}
