import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from 'styles/Home.module.css'
import data from '../Data/education.json'
import { useState } from 'react'
import Link from 'next/link'
import Image from 'next/image'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(data);
  const [information, setInformation] = useState([...data])

  
  
  return (
    <>
      <Head>
        <title>Employee Webpage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>


        <div className={styles.description}>
          <p className={styles.about__btn}>
           <Link className='about-btn' href="about">Meet the team</Link>
          </p>
          
        </div>

        <div className={styles.welcome__area}>
          <h1>Welcome!</h1>
          <p>Big Company CO.</p>
        </div>

        

       <Link href="/" className={styles.links}>Home</Link>
       <Link href="../about" className={styles.links}>About</Link>
       <Link href="/" className={styles.link}>Join</Link>

      

      <div className={styles.background}>

      </div>

      
      <div className={styles.about__company}>
        <h2>Big Company Co. is a company that values customer satisfaction <br></br> and good company enviornemnt for employees</h2> 
      </div>

      <div className={styles.main__page__images}>
       
      </div>



        
      </main>
    </>
  )
}
